name: Linting Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install htmlhint stylelint --save-dev

      # Step 3: Lint HTML files
      - name: Lint HTML files
        run: npx htmlhint "src/**/*.html"

      # Step 4: Lint CSS files
      - name: Lint CSS files
        run: npx stylelint "styles/**/*.css"
